/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ust.keysim.ui;

import KeySim.KeySimManager;
import com.ust.keysim.ui.misc.CustomOutputStream;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author u55369
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        initUI();
        // System.setOut(new PrintStream(new CustomOutputStream(logTextArea, System.out)));
        System.out.println("UI Initialized");

        initBackEnd();

    }

    private Map<String, List<String>> operationMap;
    private List<List<String>> dataList;

    private void initBackEnd() {
        File input = new File(UIGlobals.configFile);
        if (input.exists() && input.isFile()) {
            operationMap = BackEndUtils.getOperationMap(UIGlobals.configFile);
            loadOperations();
        } else {
            System.err.println("Failed to load default config file : " + UIGlobals.configFile);
        }

        input = new File(UIGlobals.dataFile);
        if (input.exists() && input.isFile()) {
            dataList = BackEndUtils.getDataList(UIGlobals.dataFile);
            loadDataTable();
        } else {
            System.err.println("Failed to load default data file : " + UIGlobals.dataFile);
        }
    }

    private void loadOperations() {
        operationsComboBox.removeAllItems();
        for (String key : operationMap.keySet()) {
            operationsComboBox.addItem(key);
        }
    }

    private void loadDataTable() {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("#", noColAdd());

        for (List list : dataList) {
            Vector temp = new Vector(list);
            temp.remove(0);
            tableModel.addColumn(list.get(0), temp);
        }
        dataTable.setModel(tableModel);
    }

    private Vector noColAdd() {
        int maxCount = 0;
        for (List list : dataList) {
            if (maxCount < list.size()) {
                maxCount = list.size();
            }
        }
        Vector nos = new Vector();
        for (int i = 1; i < maxCount; i++) {
            nos.add(i);
        }
        return nos;
    }

    private void initUI() {
        setIconImage(getIcon());
        // this.setVisible(false);
    }

    private Image getIcon() {
        ImageIcon imageIcon = new ImageIcon("res/icon.png");
        return imageIcon.getImage();
    }

    private Dimension getDimension() {
        return Toolkit.getDefaultToolkit().getScreenSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowTitleFinder = new javax.swing.JFrame();
        windowTitleMainPanel = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        windowMonitorStart = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(32767, 0));
        headLabel = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(32767, 0));
        windowMonitorStop = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 32767));
        jScrollPane3 = new javax.swing.JScrollPane();
        ouputView = new javax.swing.JTextPane();
        footer = new javax.swing.JPanel();
        viewPosition = new javax.swing.JButton();
        mousePositionFinder = new javax.swing.JFrame();
        mouseMainPanel = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        testKeys = new javax.swing.JFrame();
        testPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        errorMsg = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        disPlayPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        operationLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        stopSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startSpinner = new javax.swing.JSpinner();
        operationsComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        reloadButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        formResizeLabel = new javax.swing.JLabel();
        miscPanel = new javax.swing.JPanel();
        miscPane = new javax.swing.JTabbedPane();
        operationPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lookUpOpFile = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        opFileName = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        opList = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lookUpDataFile = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        dataFileName = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        logPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        toolMenu = new javax.swing.JMenu();
        windowTitleFinderMenu = new javax.swing.JMenuItem();
        testKeysMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contact = new javax.swing.JMenuItem();

        windowTitleFinder.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        windowTitleFinder.setTitle("Window Title Finder");
        windowTitleFinder.setAlwaysOnTop(true);
        windowTitleFinder.setIconImage(getIcon());
        windowTitleFinder.setLocationByPlatform(true);
        windowTitleFinder.setMinimumSize(new java.awt.Dimension(420, 370));
        windowTitleFinder.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowTitleFinderWindowClosed(evt);
            }
        });

        windowTitleMainPanel.setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setPreferredSize(new java.awt.Dimension(100, 50));

        windowMonitorStart.setText("Start");
        windowMonitorStart.setPreferredSize(new java.awt.Dimension(70, 35));
        windowMonitorStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowMonitorStartActionPerformed(evt);
            }
        });
        header.add(windowMonitorStart);
        header.add(filler5);

        headLabel.setForeground(new java.awt.Color(255, 255, 255));
        headLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headLabel.setText("Click Start to begin Window Monitoring");
        headLabel.setMaximumSize(new java.awt.Dimension(80, 50));
        headLabel.setPreferredSize(new java.awt.Dimension(200, 50));
        header.add(headLabel);
        header.add(filler6);

        windowMonitorStop.setText("Stop");
        windowMonitorStop.setPreferredSize(new java.awt.Dimension(70, 30));
        windowMonitorStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowMonitorStopActionPerformed(evt);
            }
        });
        header.add(windowMonitorStop);

        windowTitleMainPanel.add(header, java.awt.BorderLayout.NORTH);

        content.setBackground(new java.awt.Color(51, 51, 51));
        content.setLayout(new java.awt.BorderLayout());
        content.add(filler1, java.awt.BorderLayout.LINE_START);
        content.add(filler2, java.awt.BorderLayout.LINE_END);
        content.add(filler3, java.awt.BorderLayout.PAGE_END);
        content.add(filler4, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setViewportView(ouputView);

        content.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        windowTitleMainPanel.add(content, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(51, 51, 51));
        footer.setForeground(new java.awt.Color(255, 255, 255));
        footer.setMinimumSize(new java.awt.Dimension(100, 100));

        viewPosition.setText("View Co-ordinates");
        viewPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPositionActionPerformed(evt);
            }
        });
        footer.add(viewPosition);

        windowTitleMainPanel.add(footer, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout windowTitleFinderLayout = new javax.swing.GroupLayout(windowTitleFinder.getContentPane());
        windowTitleFinder.getContentPane().setLayout(windowTitleFinderLayout);
        windowTitleFinderLayout.setHorizontalGroup(
            windowTitleFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowTitleMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        windowTitleFinderLayout.setVerticalGroup(
            windowTitleFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowTitleMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        mousePositionFinder.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        mousePositionFinder.setTitle("Mouse Location Finder");
        mousePositionFinder.setAlwaysOnTop(true);
        mousePositionFinder.setMinimumSize(getDimension());
        mousePositionFinder.setUndecorated(true);
        mousePositionFinder.setOpacity(0.6F);

        mouseMainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mouseMainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseMainPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseMainPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mouseMainPanelMouseReleased(evt);
            }
        });

        close.setText("x");
        close.setIconTextGap(2);
        close.setOpaque(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mouseMainPanelLayout = new javax.swing.GroupLayout(mouseMainPanel);
        mouseMainPanel.setLayout(mouseMainPanelLayout);
        mouseMainPanelLayout.setHorizontalGroup(
            mouseMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mouseMainPanelLayout.createSequentialGroup()
                .addGap(0, 447, Short.MAX_VALUE)
                .addComponent(close))
        );
        mouseMainPanelLayout.setVerticalGroup(
            mouseMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mouseMainPanelLayout.createSequentialGroup()
                .addComponent(close)
                .addGap(0, 280, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mousePositionFinderLayout = new javax.swing.GroupLayout(mousePositionFinder.getContentPane());
        mousePositionFinder.getContentPane().setLayout(mousePositionFinderLayout);
        mousePositionFinderLayout.setHorizontalGroup(
            mousePositionFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mouseMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mousePositionFinderLayout.setVerticalGroup(
            mousePositionFinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mouseMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        testKeys.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        testKeys.setTitle("Test Operations");
        testKeys.setAlwaysOnTop(true);
        testKeys.setIconImage(getIcon());
        testKeys.setLocationByPlatform(true);
        testKeys.setSize(new java.awt.Dimension(400, 300));
        testKeys.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                testKeysWindowClosing(evt);
            }
        });

        testPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setText("Enter the operations to test");

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Start");

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stop ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        jLabel11.setText("Enter the test Data");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        jButton1.setText("Start");

        jButton2.setText("Stop");

        javax.swing.GroupLayout testPanelLayout = new javax.swing.GroupLayout(testPanel);
        testPanel.setLayout(testPanelLayout);
        testPanelLayout.setHorizontalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(testPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(testPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(testPanelLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(49, 49, 49)
                                .addComponent(jButton2))
                            .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(jSpinner4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        testPanelLayout.setVerticalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(testPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(testPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout testKeysLayout = new javax.swing.GroupLayout(testKeys.getContentPane());
        testKeys.getContentPane().setLayout(testKeysLayout);
        testKeysLayout.setHorizontalGroup(
            testKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        testKeysLayout.setVerticalGroup(
            testKeysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fileChooser.setApproveButtonToolTipText("Open File");
        fileChooser.setBackground(new java.awt.Color(51, 51, 51));
        fileChooser.setCurrentDirectory(new java.io.File("\\\\"));
            fileChooser.setDialogTitle("Please Choose the file");
            fileChooser.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fileChooserActionPerformed(evt);
                }
            });

            errorMsg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            errorMsg.setTitle("Error");
            errorMsg.setAlwaysOnTop(true);
            errorMsg.setLocationByPlatform(true);
            errorMsg.setResizable(false);
            errorMsg.setSize(new java.awt.Dimension(300, 250));
            errorMsg.setType(java.awt.Window.Type.UTILITY);
            errorMsg.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    errorMsgWindowClosing(evt);
                }
            });

            jPanel5.setBackground(new java.awt.Color(51, 51, 51));
            jPanel5.setPreferredSize(new java.awt.Dimension(300, 250));

            errorLabel.setForeground(new java.awt.Color(255, 255, 255));
            errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            errorMessage.setForeground(new java.awt.Color(255, 255, 255));
            errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            errorMessage.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true), "Error Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout errorMsgLayout = new javax.swing.GroupLayout(errorMsg.getContentPane());
            errorMsg.getContentPane().setLayout(errorMsgLayout);
            errorMsgLayout.setHorizontalGroup(
                errorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            errorMsgLayout.setVerticalGroup(
                errorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("KeySim");
            setAlwaysOnTop(true);
            setBackground(new java.awt.Color(102, 102, 102));
            setLocationByPlatform(true);
            setMinimumSize(new java.awt.Dimension(220, 410));
            setName("MainFrame"); // NOI18N
            setSize(new java.awt.Dimension(570, 445));
            getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

            controlPanel.setBackground(new java.awt.Color(51, 51, 51));
            controlPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            controlPanel.setForeground(new java.awt.Color(255, 255, 255));
            controlPanel.setMaximumSize(new java.awt.Dimension(210, 410));
            controlPanel.setMinimumSize(new java.awt.Dimension(210, 410));
            controlPanel.setPreferredSize(new java.awt.Dimension(210, 410));

            disPlayPanel.setBackground(new java.awt.Color(51, 51, 51));
            disPlayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true), "Info", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 255, 255))); // NOI18N

            jLabel3.setBackground(new java.awt.Color(51, 51, 51));
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setText("Count         :");
            jLabel3.setToolTipText("");

            countLabel.setBackground(new java.awt.Color(51, 51, 51));
            countLabel.setForeground(new java.awt.Color(255, 255, 255));

            jLabel5.setBackground(new java.awt.Color(51, 51, 51));
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setText("Operation   :");

            operationLabel.setBackground(new java.awt.Color(51, 51, 51));
            operationLabel.setForeground(new java.awt.Color(255, 255, 255));
            operationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            operationLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

            jLabel7.setBackground(new java.awt.Color(51, 51, 51));
            jLabel7.setForeground(new java.awt.Color(255, 255, 255));
            jLabel7.setText("Status        :");

            statusLabel.setBackground(new java.awt.Color(51, 51, 51));
            statusLabel.setForeground(new java.awt.Color(255, 255, 255));
            statusLabel.setText("Not running");

            javax.swing.GroupLayout disPlayPanelLayout = new javax.swing.GroupLayout(disPlayPanel);
            disPlayPanel.setLayout(disPlayPanelLayout);
            disPlayPanelLayout.setHorizontalGroup(
                disPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(disPlayPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(disPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(disPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(countLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(operationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            disPlayPanelLayout.setVerticalGroup(
                disPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(disPlayPanelLayout.createSequentialGroup()
                    .addGroup(disPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(disPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(countLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(disPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(disPlayPanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(0, 31, Short.MAX_VALUE))
                        .addComponent(operationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );

            inputPanel.setBackground(new java.awt.Color(51, 51, 51));
            inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true), "Inputs", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 255, 255))); // NOI18N

            stopSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

            jLabel1.setBackground(new java.awt.Color(51, 51, 51));
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Start");

            jLabel2.setBackground(new java.awt.Color(51, 51, 51));
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("Stop ");

            startSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

            operationsComboBox.setBackground(new java.awt.Color(51, 51, 51));
            operationsComboBox.setForeground(new java.awt.Color(0, 0, 0));
            operationsComboBox.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    operationsComboBoxItemStateChanged(evt);
                }
            });

            jLabel9.setBackground(new java.awt.Color(51, 51, 51));
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setText("Selected Operation");

            javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
            inputPanel.setLayout(inputPanelLayout);
            inputPanelLayout.setHorizontalGroup(
                inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inputPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(inputPanelLayout.createSequentialGroup()
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(startSpinner)
                                .addComponent(stopSpinner)))
                        .addGroup(inputPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(operationsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            inputPanelLayout.setVerticalGroup(
                inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(operationsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stopSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(20, 20, 20))
            );

            buttonPanel.setBackground(new java.awt.Color(51, 51, 51));
            buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true), "Controls", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 255, 255))); // NOI18N

            startButton.setBackground(new java.awt.Color(51, 51, 51));
            startButton.setForeground(new java.awt.Color(0, 0, 0));
            startButton.setText("Start");
            startButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    startButtonActionPerformed(evt);
                }
            });

            stopButton.setBackground(new java.awt.Color(51, 51, 51));
            stopButton.setForeground(new java.awt.Color(0, 0, 0));
            stopButton.setText("Stop");
            stopButton.setEnabled(false);
            stopButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    stopButtonActionPerformed(evt);
                }
            });

            reloadButton.setBackground(new java.awt.Color(51, 51, 51));
            reloadButton.setForeground(new java.awt.Color(0, 0, 0));
            reloadButton.setText("Reload ");

            jButton4.setBackground(new java.awt.Color(51, 51, 51));
            jButton4.setForeground(new java.awt.Color(0, 0, 0));
            jButton4.setText("jButton4");

            javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
            buttonPanel.setLayout(buttonPanelLayout);
            buttonPanelLayout.setHorizontalGroup(
                buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(reloadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stopButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
            );
            buttonPanelLayout.setVerticalGroup(
                buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stopButton)
                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reloadButton)
                        .addComponent(jButton4)))
            );

            formResizeLabel.setBackground(new java.awt.Color(153, 255, 255));
            formResizeLabel.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
            formResizeLabel.setForeground(new java.awt.Color(0, 0, 0));
            formResizeLabel.setText("◄");
            formResizeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
            formResizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    formResizeLabelMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
            controlPanel.setLayout(controlPanelLayout);
            controlPanelLayout.setHorizontalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(disPlayPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(formResizeLabel)
                    .addGap(15, 15, 15))
            );
            controlPanelLayout.setVerticalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(formResizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                            .addComponent(disPlayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())))
            );

            getContentPane().add(controlPanel);

            miscPanel.setBackground(new java.awt.Color(51, 51, 51));
            miscPanel.setPreferredSize(new java.awt.Dimension(400, 0));
            miscPanel.setLayout(new java.awt.GridLayout());

            miscPane.setBackground(new java.awt.Color(102, 102, 102));
            miscPane.setForeground(new java.awt.Color(0, 0, 0));
            miscPane.setMinimumSize(new java.awt.Dimension(76, 40));
            miscPane.setPreferredSize(new java.awt.Dimension(350, 340));

            operationPanel.setBackground(new java.awt.Color(51, 51, 51));
            operationPanel.setPreferredSize(new java.awt.Dimension(420, 369));
            operationPanel.setLayout(new java.awt.BorderLayout());

            jPanel1.setBackground(new java.awt.Color(51, 51, 51));
            jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 1, true));
            jPanel1.setPreferredSize(new java.awt.Dimension(200, 60));

            jLabel12.setBackground(new java.awt.Color(51, 51, 51));
            jLabel12.setForeground(new java.awt.Color(255, 255, 255));
            jLabel12.setText("File : ");

            lookUpOpFile.setBackground(new java.awt.Color(51, 51, 51));
            lookUpOpFile.setForeground(new java.awt.Color(0, 0, 0));
            lookUpOpFile.setText("Look Up");
            lookUpOpFile.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    lookUpOpFileActionPerformed(evt);
                }
            });

            jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

            opFileName.setEditable(false);
            opFileName.setBackground(new java.awt.Color(51, 51, 51));
            opFileName.setColumns(20);
            opFileName.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
            opFileName.setForeground(new java.awt.Color(255, 255, 255));
            opFileName.setLineWrap(true);
            opFileName.setRows(5);
            jScrollPane7.setViewportView(opFileName);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lookUpOpFile)
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(lookUpOpFile))
                            .addGap(0, 14, Short.MAX_VALUE)))
                    .addContainerGap())
            );

            operationPanel.add(jPanel1, java.awt.BorderLayout.NORTH);

            jPanel4.setBackground(new java.awt.Color(51, 51, 51));

            opList.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    opListKeyTyped(evt);
                }
            });
            jScrollPane4.setViewportView(opList);

            jLabel13.setText("Operations ");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            operationPanel.add(jPanel4, java.awt.BorderLayout.LINE_START);

            miscPane.addTab("Operations", operationPanel);

            dataPanel.setBackground(new java.awt.Color(51, 51, 51));
            dataPanel.setPreferredSize(new java.awt.Dimension(420, 369));
            dataPanel.setLayout(new java.awt.BorderLayout());

            jPanel2.setBackground(new java.awt.Color(51, 51, 51));
            jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 1, true));
            jPanel2.setPreferredSize(new java.awt.Dimension(400, 60));

            jLabel10.setBackground(new java.awt.Color(51, 51, 51));
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setText("File : ");

            lookUpDataFile.setBackground(new java.awt.Color(51, 51, 51));
            lookUpDataFile.setForeground(new java.awt.Color(0, 0, 0));
            lookUpDataFile.setText("Look Up");
            lookUpDataFile.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    lookUpDataFileActionPerformed(evt);
                }
            });

            jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

            dataFileName.setEditable(false);
            dataFileName.setBackground(new java.awt.Color(51, 51, 51));
            dataFileName.setColumns(20);
            dataFileName.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
            dataFileName.setForeground(new java.awt.Color(255, 255, 255));
            dataFileName.setLineWrap(true);
            dataFileName.setRows(5);
            jScrollPane8.setViewportView(dataFileName);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lookUpDataFile)
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lookUpDataFile)
                                .addComponent(jLabel10))
                            .addGap(0, 14, Short.MAX_VALUE)))
                    .addContainerGap())
            );

            dataPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

            jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Table", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
            jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

            dataTable.setBackground(new java.awt.Color(102, 102, 102));
            dataTable.setForeground(new java.awt.Color(255, 255, 255));
            dataTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            dataTable.setGridColor(new java.awt.Color(0, 255, 255));
            jScrollPane1.setViewportView(dataTable);

            dataPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

            miscPane.addTab("Data", dataPanel);

            logPanel.setBackground(new java.awt.Color(51, 51, 51));

            jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
            jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)), "Log", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 204, 204))); // NOI18N

            logTextArea.setEditable(false);
            logTextArea.setBackground(new java.awt.Color(51, 51, 51));
            logTextArea.setColumns(20);
            logTextArea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
            logTextArea.setForeground(new java.awt.Color(255, 255, 255));
            logTextArea.setRows(5);
            jScrollPane2.setViewportView(logTextArea);

            javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
            logPanel.setLayout(logPanelLayout);
            logPanelLayout.setHorizontalGroup(
                logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addContainerGap())
            );
            logPanelLayout.setVerticalGroup(
                logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addContainerGap())
            );

            miscPane.addTab("Log", logPanel);

            miscPanel.add(miscPane);

            getContentPane().add(miscPanel);

            menuBar.setBackground(new java.awt.Color(51, 51, 51));

            toolMenu.setBackground(new java.awt.Color(51, 51, 51));
            toolMenu.setForeground(new java.awt.Color(0, 0, 0));
            toolMenu.setText("Tools");

            windowTitleFinderMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
            windowTitleFinderMenu.setForeground(new java.awt.Color(0, 0, 0));
            windowTitleFinderMenu.setText("Window Title Finder");
            windowTitleFinderMenu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    windowTitleFinderMenuActionPerformed(evt);
                }
            });
            toolMenu.add(windowTitleFinderMenu);

            testKeysMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
            testKeysMenu.setBackground(new java.awt.Color(51, 51, 51));
            testKeysMenu.setForeground(new java.awt.Color(0, 0, 0));
            testKeysMenu.setText("Operation Test");
            testKeysMenu.setToolTipText("");
            testKeysMenu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    testKeysMenuActionPerformed(evt);
                }
            });
            toolMenu.add(testKeysMenu);

            menuBar.add(toolMenu);

            helpMenu.setBackground(new java.awt.Color(51, 51, 51));
            helpMenu.setForeground(new java.awt.Color(0, 0, 0));
            helpMenu.setText("Help");

            contact.setForeground(new java.awt.Color(0, 0, 0));
            contact.setText("Contact");
            helpMenu.add(contact);

            menuBar.add(helpMenu);

            setJMenuBar(menuBar);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private KeySimManager keySimManager;

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        startKeySim();
    }//GEN-LAST:event_startButtonActionPerformed
    private void startKeySim() {
        new Thread() {
            public void run() {
                int start = (int) startSpinner.getValue();
                int stop = (int) stopSpinner.getValue();
                List<String> ops = operationMap.get(operationsComboBox.getSelectedItem());
                List<List<String>> data = dataList;
                Map<String, List<String>> doMap = new HashMap();
                if (start > stop) {
                    showError();
                } else {
                    startButton.setEnabled(false);
                    stopButton.setEnabled(true);
                    keySimManager = new KeySimManager(start, stop, ops, dataList, doMap, true);
                    keySimManager.start();

                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    monitor();
                }
            }
        }.start();
    }

    private void monitor() {
        Thread monitor = new Thread() {
            public void run() {
                while (!(keySimManager.getStatus() == Thread.State.TERMINATED)) {

                    statusLabel.setText("Running");
                    countLabel.setText(keySimManager.getCount());
                    operationLabel.setText(UiUtils.textFormat1(keySimManager.getCurrentOp()));
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                statusLabel.setText("Terminated");

                stopButton.setEnabled(false);
                startButton.setEnabled(true);
            }
        };
        monitor.run();
    }

    private void windowTitleFinderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowTitleFinderMenuActionPerformed
        // TODO add your handling code here:
        openWindowTitleFinder();
    }//GEN-LAST:event_windowTitleFinderMenuActionPerformed

    private void openWindowTitleFinder() {
        this.setState(ICONIFIED);
        windowTitleFinder.setVisible(true);
        windowTitleFinder.show();
    }

    private final int UI_WIDTH_N = 225;
    private final int UI_WIDTH_E = 600;
    private final int UI_HEIGHT = 460;

    private void formResizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formResizeLabelMouseClicked
        // TODO add your handling code here:
        if (formResizeLabel.getText().equals("►")) {
            formResizeLabel.setText("◄");
            this.setSize(UI_WIDTH_E, UI_HEIGHT);
        } else {
            formResizeLabel.setText("►");
            this.setSize(UI_WIDTH_N, UI_HEIGHT);
        }
    }//GEN-LAST:event_formResizeLabelMouseClicked

    private void windowMonitorStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowMonitorStartActionPerformed

        headLabel.setText("Click \"Stop\" to Stop Window Monitoring");
        ouputView.setText("");
        UiUtils.setCheckWindow(true);
        windowMonitorStop.setEnabled(true);
        windowMonitorStart.setEnabled(false);
        UiUtils.showWindowTitles(ouputView);
    }//GEN-LAST:event_windowMonitorStartActionPerformed

    private void windowMonitorStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowMonitorStopActionPerformed

        headLabel.setText("Click Start to begin window monitoring");
        windowMonitorStop.setEnabled(false);
        windowMonitorStart.setEnabled(true);
        UiUtils.setCheckWindow(false);
    }//GEN-LAST:event_windowMonitorStopActionPerformed

    private void viewPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPositionActionPerformed
        // TODO add your handling code here:
        windowTitleFinder.setExtendedState(ICONIFIED);
        //windowTitleFinder.setMinimumSize(new Dimension(0, 0));
        // windowTitleFinder.setSize(0, 0);
        // windowTitleFinder.setLocation(2000, 800);
        mousePositionFinder.setVisible(true);
        mousePositionFinder.show();
    }//GEN-LAST:event_viewPositionActionPerformed

    private void windowTitleFinderWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowTitleFinderWindowClosed
        // TODO add your handling code here:
        this.setState(NORMAL);
        this.setSize(UI_WIDTH_E, UI_HEIGHT);
    }//GEN-LAST:event_windowTitleFinderWindowClosed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed

        UiUtils.updateOutput(ouputView);
        mousePositionFinder.dispose();
        windowTitleFinder.setExtendedState(NORMAL);
    }//GEN-LAST:event_closeActionPerformed

    private void mouseMainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMainPanelMouseClicked
        // TODO add your handling code here:
        UiUtils.panelMouseClicked(evt);
    }//GEN-LAST:event_mouseMainPanelMouseClicked

    private void mouseMainPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMainPanelMousePressed
        // TODO add your handling code here:
        UiUtils.panelMousePressed(evt, mouseMainPanel);
    }//GEN-LAST:event_mouseMainPanelMousePressed

    private void mouseMainPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMainPanelMouseReleased
        // TODO add your handling code here:
        UiUtils.panelMouseReleased(evt, mouseMainPanel);
    }//GEN-LAST:event_mouseMainPanelMouseReleased

    private void lookUpDataFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpDataFileActionPerformed
        // TODO add your handling code here:

        fileChooser.showOpenDialog(this);

        if (fileChooser.getSelectedFile() != null) {
            System.out.println("Data File Chosen : " + fileChooser.getSelectedFile().getAbsolutePath());
            dataFileName.setText(fileChooser.getSelectedFile().getAbsolutePath());
            dataList = BackEndUtils.getDataList(fileChooser.getSelectedFile().getAbsolutePath());

            loadDataTable();
        }

//        JFileChooser fc = new JFileChooser();
//        fc.setFileFilter(new FileNameExtensionFilter("Excel files", "xlsx"));
//        fc.showOpenDialog(this);
//
//        if (fc.getSelectedFile() != null) {
//            //.setComponentFile(fc.getSelectedFile().getAbsolutePath());
//            //tableLoad();
//           // compFileName.setText(fc.getSelectedFile().getAbsolutePath());
//        }
    }//GEN-LAST:event_lookUpDataFileActionPerformed

    private void opListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opListKeyTyped

        System.out.println(evt);

    }//GEN-LAST:event_opListKeyTyped

    private void testKeysMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testKeysMenuActionPerformed
        openTestKeys();
    }//GEN-LAST:event_testKeysMenuActionPerformed

    private void testKeysWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_testKeysWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_testKeysWindowClosing

    private void lookUpOpFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpOpFileActionPerformed

        fileChooser.showOpenDialog(this);

        if (fileChooser.getSelectedFile() != null) {
            System.out.println("Config File Chosen : " + fileChooser.getSelectedFile().getAbsolutePath());
            opFileName.setText(fileChooser.getSelectedFile().getAbsolutePath());
            operationMap = BackEndUtils.getOperationMap(fileChooser.getSelectedFile().getAbsolutePath());
            loadOperations();
            loadOperationList();
        }
    }//GEN-LAST:event_lookUpOpFileActionPerformed

    private void operationsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_operationsComboBoxItemStateChanged
        loadOperationList();
    }//GEN-LAST:event_operationsComboBoxItemStateChanged

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileChooserActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
        stopButton.setEnabled(false);
        startButton.setEnabled(true);

        keySimManager.stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void errorMsgWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_errorMsgWindowClosing
        // TODO add your handling code here:
        this.setEnabled(true);
    }//GEN-LAST:event_errorMsgWindowClosing
    private void loadOperationList() {
        String key = (String) operationsComboBox.getSelectedItem();
        if (key != null && operationMap != null) {
            DefaultListModel model = new DefaultListModel();
            for (String s : operationMap.get(key)) {
                model.addElement(s);
            }
            opList.setModel(model);
        }
    }

    private void openTestKeys() {
        this.setVisible(false);
        testKeys.setVisible(true);
    }

    private void showError() {
        errorMsg.setVisible(true);
        this.setEnabled(false);

        errorLabel.setText("Error in Start and Stop Values");
        errorMessage.setText(UiUtils.textFormat("The Start value is greater than Stop value."
                + " <br>Please correct the values"));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton close;
    private javax.swing.JMenuItem contact;
    private javax.swing.JPanel content;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextArea dataFileName;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JTable dataTable;
    private javax.swing.JPanel disPlayPanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JDialog errorMsg;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel formResizeLabel;
    private javax.swing.JLabel headLabel;
    private javax.swing.JPanel header;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel logPanel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JButton lookUpDataFile;
    private javax.swing.JButton lookUpOpFile;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane miscPane;
    private javax.swing.JPanel miscPanel;
    private javax.swing.JPanel mouseMainPanel;
    private javax.swing.JFrame mousePositionFinder;
    private javax.swing.JTextArea opFileName;
    private javax.swing.JList<String> opList;
    private javax.swing.JLabel operationLabel;
    private javax.swing.JPanel operationPanel;
    private javax.swing.JComboBox<String> operationsComboBox;
    private static javax.swing.JTextPane ouputView;
    private javax.swing.JButton reloadButton;
    private javax.swing.JButton startButton;
    private javax.swing.JSpinner startSpinner;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton stopButton;
    private javax.swing.JSpinner stopSpinner;
    private javax.swing.JFrame testKeys;
    private javax.swing.JMenuItem testKeysMenu;
    private javax.swing.JPanel testPanel;
    private javax.swing.JMenu toolMenu;
    private javax.swing.JButton viewPosition;
    private javax.swing.JButton windowMonitorStart;
    private javax.swing.JButton windowMonitorStop;
    private javax.swing.JFrame windowTitleFinder;
    private javax.swing.JMenuItem windowTitleFinderMenu;
    private javax.swing.JPanel windowTitleMainPanel;
    // End of variables declaration//GEN-END:variables
}
