/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Misc.Position;
import GUI.Misc.Click;
import GUI.Misc.Rect;
import Operations.WindowUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author u55369
 */
public class WindowTitleFinder extends javax.swing.JFrame {

    /**
     * Creates new form WindowUI
     */
    public WindowTitleFinder() {
        initComponents();
        this.setTitle("Window Monitor");
        stop.setEnabled(false);
    }

    private boolean checkWindow = false;
    private static Position position;
    private static WindowTitleFinder obj;

    public static void setPosition(Position position) {
        WindowTitleFinder.position = position;
        loadPosition();
    }

    private static void loadPosition() {
        String data = "";
        for (Click click : position.getClickList()) {
            data = data + click.getName() + " : " + "(" + click.getX() + "," + click.getY() + ")" + "\n";
        }
        for (Rect rect : position.getRectList()) {
            data = data + rect.getName() + " : " + "(" + rect.getPressX() + "," + rect.getPressY() + ")" + " , "
                    + "(" + rect.getReleaseX() + "," + rect.getReleaseY() + ")" + "\n";
        }

        ouputView.setText(ouputView.getText() + data);
        obj.setMinimumSize(new Dimension(420, 400));
        obj.setSize(420, 400);
        obj.setLocation((int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth() / 1.5),
                (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() / 3.5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(32767, 0));
        headLabel = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(32767, 0));
        stop = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        viewPosition = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 32767));
        jScrollPane2 = new javax.swing.JScrollPane();
        ouputView = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(900, 150));
        setMinimumSize(new java.awt.Dimension(420, 400));
        setType(java.awt.Window.Type.UTILITY);

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setPreferredSize(new java.awt.Dimension(100, 50));

        start.setText("Start");
        start.setPreferredSize(new java.awt.Dimension(70, 35));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        header.add(start);
        header.add(filler5);

        headLabel.setForeground(new java.awt.Color(255, 255, 255));
        headLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headLabel.setText("Click Start to begin Window Monitoring");
        headLabel.setMaximumSize(new java.awt.Dimension(80, 50));
        headLabel.setPreferredSize(new java.awt.Dimension(200, 50));
        header.add(headLabel);
        header.add(filler6);

        stop.setText("Stop");
        stop.setPreferredSize(new java.awt.Dimension(70, 30));
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        header.add(stop);

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));

        viewPosition.setText("View Co-ordinates");
        viewPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPositionActionPerformed(evt);
            }
        });
        jPanel1.add(viewPosition);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        content.setBackground(new java.awt.Color(51, 51, 51));
        content.setLayout(new java.awt.BorderLayout());
        content.add(filler1, java.awt.BorderLayout.LINE_START);
        content.add(filler2, java.awt.BorderLayout.LINE_END);
        content.add(filler3, java.awt.BorderLayout.PAGE_END);
        content.add(filler4, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setViewportView(ouputView);

        content.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed

        headLabel.setText("Click Start to begin window monitoring");
        stop.setEnabled(false);
        start.setEnabled(true);
        checkWindow = false;
    }//GEN-LAST:event_stopActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        headLabel.setText("Click Stop to Stop Window Monitoring");
        ouputView.setText("");
        checkWindow = true;
        stop.setEnabled(true);
        start.setEnabled(false);
        showWindowTitles();
    }//GEN-LAST:event_startActionPerformed

    private void viewPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPositionActionPerformed
        // TODO add your handling code here:
        //this.setExtendedState(ICONIFIED);
        this.setMinimumSize(new Dimension(0, 0));
        this.setSize(0, 0);
        this.setLocation(2000, 800);
        WindowPositionFinder.main(new String[0]);

    }//GEN-LAST:event_viewPositionActionPerformed
    private void showWindowTitles() {

        new Thread() {
            @Override
            public void run() {
                String currentWindow = "";
                String oldWindow = "";
                while (checkWindow) {

                    while (currentWindow.equals(oldWindow)) {

                        currentWindow = WindowUtil.getWindowTitle();
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(WindowTitleFinder.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    oldWindow = currentWindow;
                    if (!currentWindow.equals("")) {
                        ouputView.setText(ouputView.getText() + currentWindow + "\n");
                    }
                }
            }
        }.start();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowTitleFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowTitleFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowTitleFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowTitleFinder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                obj = new WindowTitleFinder();
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel headLabel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextPane ouputView;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    private javax.swing.JButton viewPosition;
    // End of variables declaration//GEN-END:variables
}
